### ISSUE TITLE
Support SBT 1.4.x.

### ISSUE THREAD

**Issue by Caparow** [JetBrains/sbt-tc-logger#23]
With `sbt-tc-logger` version 6.0.0, TC builds fail with exit code 1 if the SBT project version is set to 1.4.x.

**Comment by cbrunnkvist** [comment]
Cross-linking the [related ticket TW-68077](https://youtrack.jetbrains.com/issue/TW-68077).

**Comment by Caparow** [comment]
The issue was not in this plugin but in one of ours.
