### ISSUE TITLE
SBT Logging too verbose despite logging not required.

### ISSUE THREAD

**Issue by fractal** [JetBrains/sbt-tc-logger#4]
I'm using the latest SNAPSHOT, and i can't avoid this logger from showing every line that SBT generates as DEBUG, even though my logLevel is set to INFO and I'm explicitly calling sbt with --info

Example messages produced:

[Step 1/1] 

Initial source changes: 

	removed:Set()

	added: Set(/data/....)

	modified: Set()

	Removed products: Set()

	External API changes: API Changes: Set()

	Modified binary dependencies: Set()

	Initial directly invalidated sources: Set(/data...)

	Sources indirectly invalidated by:

	product: Set()

	binary dep: Set()

	external source: Set()

SBT is 0.13.6

Build.scala

    logLevel := Level.Info

Logging is correctly outputted when using the "Auto" SBT mode, but then i don't get Test registration. Using the custom plugin registers the succesful tests, but then i get flooded with logging messages, which makes the console almost unusable and slows the build.

**Comment by fractal** [comment]
A multiproject is generating nearly 70 MBs in just compilation and simple tests.

Any updates?

**Comment by shkate** [comment]
Working on this. We've found that with latest version of SBT our runner is not working at all (due to some changes they made in sbt itself). I think we will have a new version shortly with some improvement in field of its verboseness as well.  Sorry for the inconvenience.

**Comment by fractal** [comment]
Thanks for the update. 

Let me know as soon as you have any new version coming. 

Thanks

**Comment by fractal** [comment]
I'm still having issues using a Custom location for SBT (to be able to configure plugins and repos), and using the SBT-TeamCity-Logger (version 0.1.0, not snapshot) addSbtPlugin("org.jetbrains.teamcity.plugins" % "sbt-teamcity-logger" % "0.1.0") Scala compiler (8s)[10:55:24][info] Set current project to SSE (in build file:/data/elt/local0/home/eltdev/TeamCity/buildAgent3/work/fe6c08143bb88c96/)[10:55:24][info] Applying State transformations jetbrains.buildServer.sbtlogger.SbtTeamCityLogger from /data/elt/local0/home/eltdev/TeamCity/buildAgent3/temp/agentTmp/agent-sbt/tc_plugin/sbt-teamcity-logger.jar[10:55:24]java.lang.ClassNotFoundException: jetbrains.buildServer.sbtlogger.SbtTeamCityLogger$[10:55:24]	 at java.net.URLClassLoader$1.run(URLClassLoader.java:372)[10:55:24]	 at java.net.URLClassLoader$1.run(URLClassLoader.java:361)[10:55:24]	 at java.security.AccessController.doPrivileged(Native Method)[10:55:24]	 at java.net.URLClassLoader.findClass(URLClassLoader.java:360)[10:55:24]	 at java.lang.ClassLoader.loadClass(ClassLoader.java:424)

**Comment by shkate** [comment]
Sorry for the inconvenience. I will try to figure and and the fix the problem as soon as possible.

**Comment by fractal** [comment]
any updates on this?

Thanks

**Comment by fractal** [comment]
The issue in YouTrack is now closed, but this bug is still very much open. Any updates?

**Comment by fractal** [comment]
https://youtrack.jetbrains.com/issue/TW-40415

**Comment by fractal** [comment]
thanks so much. It finally works! Went from 15-30mb logs to 2-5MBs. See YouTrack item above for resolution.

**Comment by shkate** [comment]
Thanks for your patience!
